In [1]:
import numpy as np
import pandas as pd
import optuna

/home/kuangr/inoue019/.conda/envs/py39/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
ls | grep sqlite3

cmap_GATv2Conv.sqlite3
cmap_GCNConv.sqlite3
cmap_transformer.sqlite3
GATv2Conv.sqlite3
GCNConv.sqlite3
TransformerConv.sqlite3

In [3]:
study = optuna.create_study(
    storage="sqlite:///GCNConv.sqlite3",
    study_name="GCNConv",
    load_if_exists=True,
)
study.trials_dataframe().dropna().sort_values('values_1').head()

[I 2024-01-03 17:05:55,473] Using an existing study with name 'GCNConv' instead of creating a new one.

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_batch_size,params_dropout,params_drug_hidden,params_epochs,params_is_attention,params_lr,params_protein_hidden,system_attrs_nsga2:generation,state
282,282,38453.733641,40939.906684,2023-12-29 00:09:49.358490,2023-12-29 00:31:53.079391,0 days 00:22:03.720901,100,0.1,64.0,100.0,False,0.001,64.0,5,COMPLETE
359,359,38425.669961,41127.839952,2023-12-29 20:12:28.264034,2023-12-29 20:28:40.977167,0 days 00:16:12.713133,100,0.1,64.0,100.0,False,0.001,32.0,7,COMPLETE
231,231,38612.622359,41218.370334,2023-12-28 11:05:48.158600,2023-12-28 11:20:19.468454,0 days 00:14:31.309854,100,0.3,64.0,100.0,False,0.001,16.0,4,COMPLETE
327,327,38673.607414,41226.356228,2023-12-29 11:36:18.655483,2023-12-29 11:56:55.299816,0 days 00:20:36.644333,100,0.1,64.0,100.0,False,0.001,64.0,6,COMPLETE
333,333,38348.894227,41236.257243,2023-12-29 13:20:28.677483,2023-12-29 13:35:33.968305,0 days 00:15:05.290822,150,0.3,64.0,100.0,False,0.010,16.0,6,COMPLETE

In [4]:
study = optuna.create_study(
    storage="sqlite:///GATv2Conv.sqlite3",
    study_name="GATv2Conv",
    load_if_exists=True,
)
study.trials_dataframe().dropna().sort_values('values_1').head()

[I 2024-01-03 17:06:02,838] Using an existing study with name 'GATv2Conv' instead of creating a new one.

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_batch_size,params_dropout,params_drug_hidden,params_epochs,params_is_attention,params_lr,params_protein_hidden,system_attrs_nsga2:generation,state
292,292,36403.470113,39351.431369,2023-12-30 01:57:32.468175,2023-12-30 02:21:19.271812,0 days 00:23:46.803637,100,0.2,16.0,100.0,False,0.0010,32.0,5,COMPLETE
272,272,36511.159242,39644.778429,2023-12-29 18:49:38.972086,2023-12-29 19:15:18.829164,0 days 00:25:39.857078,100,0.2,32.0,100.0,False,0.0100,16.0,5,COMPLETE
201,201,36969.306172,39660.741862,2023-12-28 17:41:11.363843,2023-12-28 18:10:02.526197,0 days 00:28:51.162354,100,0.1,16.0,50.0,True,0.0001,16.0,3,COMPLETE
246,246,36594.396438,39685.779785,2023-12-29 09:15:27.155013,2023-12-29 09:38:22.933017,0 days 00:22:55.778004,150,0.2,16.0,100.0,False,0.0001,32.0,4,COMPLETE
214,214,36776.422598,39726.830675,2023-12-28 22:09:17.956731,2023-12-28 22:33:06.405363,0 days 00:23:48.448632,100,0.2,64.0,100.0,False,0.0010,16.0,4,COMPLETE

In [5]:
study = optuna.create_study(
    storage="sqlite:///TransformerConv.sqlite3",
    study_name="TransformerConv",
    load_if_exists=True,
)
study.trials_dataframe().dropna().sort_values('values_1').head()

[I 2024-01-03 17:06:08,279] Using an existing study with name 'TransformerConv' instead of creating a new one.

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_batch_size,params_dropout,params_drug_hidden,params_epochs,params_is_attention,params_lr,params_protein_hidden,system_attrs_nsga2:generation,state
247,247,34859.338227,37644.351074,2023-12-29 20:39:44.991276,2023-12-29 21:05:51.972962,0 days 00:26:06.981686,100,0.1,64.0,100.0,True,0.0010,64.0,4,COMPLETE
181,181,34707.216563,37972.135579,2023-12-28 21:12:13.714139,2023-12-28 21:37:51.262091,0 days 00:25:37.547952,150,0.1,64.0,100.0,False,0.0001,64.0,3,COMPLETE
131,131,35113.053758,38268.772135,2023-12-28 03:14:21.753067,2023-12-28 03:41:45.526269,0 days 00:27:23.773202,100,0.2,64.0,100.0,False,0.0001,64.0,2,COMPLETE
116,116,35019.484890,38354.127360,2023-12-27 21:41:32.143998,2023-12-27 22:01:40.271153,0 days 00:20:08.127155,150,0.3,64.0,100.0,False,0.0100,16.0,2,COMPLETE
124,124,35461.766156,38364.245497,2023-12-28 00:31:54.466626,2023-12-28 00:58:00.738869,0 days 00:26:06.272243,100,0.1,64.0,100.0,True,0.0010,64.0,2,COMPLETE

In [6]:
study = optuna.create_study(
    storage="sqlite:///cmap_GATv2Conv.sqlite3",
    study_name="GATv2Conv",
    load_if_exists=True,
)
study.trials_dataframe().dropna().sort_values('values_1').head()

[I 2024-01-03 17:06:10,504] Using an existing study with name 'GATv2Conv' instead of creating a new one.

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_batch_size,params_dropout,params_drug_hidden,params_epochs,params_is_attention,params_lr,params_protein_hidden,system_attrs_nsga2:generation,state
50,50,22122.739411,28049.840930,2023-12-28 06:01:34.992477,2023-12-28 08:21:57.550036,0 days 02:20:22.557559,25,0.3,16,100,True,0.010,64,1,COMPLETE
70,70,20045.260304,28055.399753,2023-12-29 13:35:09.834870,2023-12-29 16:04:21.237199,0 days 02:29:11.402329,25,0.1,32,100,True,0.001,16,1,COMPLETE
82,82,19717.946851,28181.483343,2023-12-30 07:49:55.011940,2023-12-30 09:01:01.559638,0 days 01:11:06.547698,50,0.3,16,50,False,0.001,16,1,COMPLETE
16,16,21540.191209,28209.569185,2023-12-26 23:56:26.826896,2023-12-27 00:39:46.311645,0 days 00:43:19.484749,50,0.3,16,50,True,0.001,64,0,COMPLETE
52,52,20868.699019,28233.596542,2023-12-28 10:48:28.399415,2023-12-28 13:05:50.879304,0 days 02:17:22.479889,50,0.1,64,100,False,0.010,64,1,COMPLETE

In [7]:
study = optuna.create_study(
    storage="sqlite:///cmap_GCNConv.sqlite3",
    study_name="cmap_GCNConv",
    load_if_exists=True,
)
study.trials_dataframe().dropna().sort_values('values_1').head()

[I 2024-01-03 17:06:12,394] Using an existing study with name 'cmap_GCNConv' instead of creating a new one.

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_batch_size,params_dropout,params_drug_hidden,params_epochs,params_is_attention,params_lr,params_protein_hidden,system_attrs_nsga2:generation,state
45,45,22022.190714,31189.668931,2023-12-27 20:40:53.225155,2023-12-27 21:50:17.311410,0 days 01:09:24.086255,25,0.3,64,100,True,0.0100,16,0,COMPLETE
119,119,20717.270826,31222.808841,2023-12-30 04:55:57.773966,2023-12-30 05:51:58.296975,0 days 00:56:00.523009,50,0.2,32,100,False,0.0100,16,2,COMPLETE
98,98,22508.515713,31255.371156,2023-12-29 10:17:24.379396,2023-12-29 10:50:36.178912,0 days 00:33:11.799516,25,0.1,16,50,False,0.0010,16,1,COMPLETE
90,90,21728.656835,31256.515831,2023-12-29 05:17:08.012471,2023-12-29 05:54:07.388416,0 days 00:36:59.375945,50,0.1,16,50,False,0.0010,32,1,COMPLETE
94,94,22952.316745,31377.254583,2023-12-29 08:11:16.562896,2023-12-29 08:57:04.264185,0 days 00:45:47.701289,10,0.1,32,50,False,0.0001,16,1,COMPLETE

In [8]:
study = optuna.create_study(
    storage="sqlite:///cmap_transformer.sqlite3",
    study_name="transformer",
    load_if_exists=True,
)
study.trials_dataframe().dropna().sort_values('values_1').head()

[I 2024-01-03 17:06:13,775] Using an existing study with name 'transformer' instead of creating a new one.

,number,values_0,values_1,datetime_start,datetime_complete,duration,params_batch_size,params_dropout,params_drug_hidden,params_epochs,params_is_attention,params_lr,params_protein_hidden,system_attrs_nsga2:generation,state
65,65,22749.804631,27620.638576,2023-12-29 00:07:13.933844,2023-12-29 00:44:01.950929,0 days 00:36:48.017085,50,0.2,32,50,False,0.0001,64,1,COMPLETE
91,91,20745.013016,27626.747304,2023-12-29 23:38:00.494953,2023-12-30 00:23:29.911646,0 days 00:45:29.416693,50,0.2,32,50,True,0.0010,32,1,COMPLETE
2,2,21229.293626,27806.454542,2023-12-26 12:26:01.241931,2023-12-26 13:00:26.064390,0 days 00:34:24.822459,50,0.3,32,50,False,0.0001,16,0,COMPLETE
66,66,20519.204503,27872.549420,2023-12-29 00:44:07.045191,2023-12-29 02:02:20.164150,0 days 01:18:13.118959,50,0.3,16,100,True,0.0010,32,1,COMPLETE
85,85,19190.615304,27935.679179,2023-12-29 18:42:31.907223,2023-12-29 20:02:27.916099,0 days 01:19:56.008876,50,0.2,16,100,True,0.0010,64,1,COMPLETE